kaguna/dimba-api

- .github/PULL_REQUEST_TEMPLATE.md
- Gemfile
- Gemfile.lock
- README.md
- config/application.yml.sample
- db/seeds.rb
> Seed data to db

- .circleci/config.yml
- .coveralls.yml
- Gemfile
- Gemfile.lock
- Rakefile
- spec/rails_helper.rb
- Configure codeclimate for code quality and coverage.
N/A
N/A
N/A
> Configure circle to push coverage to codeclimate

- .gitignore
- Gemfile
- Gemfile.lock
- spec/requests/teams_spec.rb
- spec/support/factory_bot.rb
- spec/support/request_helper.rb
- Configure FactoryBot and add more tests.
- Relocate the json function to its own file.
- Add gems to aid in teams factories.
- Add show teams test
- Run `rspec spec/requests/teams_spec.rb`
N/A
> Configure data generators and add tests

- README.md
- Adds the code quality and code coverage badges.
- Add code quality badge.
- Add code coverage badge.
N/A
- Code coverage should increase by testing all the necessary files.
N/A
> Add coverage and quality badges

- app/controllers/players_controller.rb
- config/routes.rb
- spec/factories/players.rb
- spec/requests/players_spec.rb
- Enables a user to perform CRUD operations on a player.
- Create a controller file to perform CRUD operations.
- Write a faker for player details.
- Test the CRUD operations
- 
- [#159732732](https://www.pivotaltracker.com/story/show/159732732)
> #159732732 Enable CRUD operations on a player.

- Gemfile
- app/controllers/fixtures_controller.rb
- config/routes.rb
- spec/factories/fixtures.rb
- spec/factories/teams.rb
- spec/requests/fixtures_spec.rb
- Enable users perform crud operations on the fixtures.
- Write all crud functions on the controller.
- Connect the via routes.
- Create bot to fake the data.
[#160252034](https://www.pivotaltracker.com/story/show/160252034)
> #160252034 Enable users perform crud operations on the fixtures

- app/models/transfer.rb
- db/migrate/20180920115637_create_users.rb
- db/migrate/20180927170652_create_transfers.rb
- db/schema.rb
- spec/models/transfer_spec.rb
- spec/requests/user_signup_spec.rb
- Creates player transfer table.
- Create transfer table.
- Add foreign keys to the related tables.
- [#159654075](https://www.pivotaltracker.com/story/show/159654075)
> #159654075 Create player transfer table.

- app/models/league.rb
- app/models/leagues_sponsor.rb
- app/models/leagues_team.rb
- app/models/sponsor.rb
- db/migrate/20180924114158_create_leagues.rb
- db/migrate/20180924115542_create_leagues_teams.rb
- db/migrate/20180924152014_add_foreign_keys.rb
- db/migrate/20180924191525_create_sponsors.rb
- db/migrate/20180924191551_create_leagues_sponsors.rb
- db/migrate/20180924201746_add_association_between_league_and_sponsor_table.rb
- db/schema.rb
- spec/models/league_spec.rb
- spec/models/leagues_sponsor_spec.rb
- spec/models/leagues_team_spec.rb
- spec/models/sponsor_spec.rb
- Creates a leagues and sponsors table.
- Create league table.
- Create an associative table between leagues and teams called leaguesTeams
- Add foreign keys
- Create sponsor table.
- Create an associative table between leagues and sponsors called leaguessponsors
- Add foreign keys
[#160414377](https://www.pivotaltracker.com/story/show/160414377)
[#160414439](https://www.pivotaltracker.com/story/show/160414439)
> Create the leagues and sponsors model

- app/models/league_fixture.rb
- db/migrate/20180924115542_create_leagues_teams.rb
- db/migrate/20180924152014_add_foreign_keys.rb
- db/migrate/20181003151200_create_league_fixtures.rb
- db/schema.rb
- spec/models/league_fixture_spec.rb
- Creates league fixture table.
- Add relationship to the leagues table.
- Add relationship to the fixtures table.
- Modify leagues teams table and add new relationships
- [#160941688](https://www.pivotaltracker.com/story/show/160941688)
> #160941688 Create league fixture table

- app/controllers/fixtures_controller.rb
- app/controllers/helpers/fixtures_controller_helper.rb
- app/models/league.rb
- app/models/leagues_team.rb
- app/models/team.rb
- app/policies/fixtures_controller_policy.rb
- config/application.rb
- config/routes.rb
- db/schema.rb
- Enable admin autogenerate fixtures in a specific league.
- 
- 
- 
- 
[#160857153](https://www.pivotaltracker.com/story/show/160857153)
> #160857153 Autogenerate fixtures in a specific league.

- app/controllers/transfer_controller.rb
- app/models/league.rb
- app/policies/transfer_policy.rb
- config/routes.rb
- spec/factories/transfers.rb
- spec/requests/transfers_spec.rb
- Enable the assigned officials' transfer player from one team to another
- Write tests
- Write policy such that only the official can do the action.
- Save the transfers
- [#159653966](https://www.pivotaltracker.com/story/show/159653966)
- In order to fix the failing tests here, PR [#33](https://github.com/kaguna/dimba-api/pull/33) must be merged first.
> #159653966 Allow player transfer to another team

- app/models/user.rb
- db/seeds.rb
- Add official roles to the roles model.
- Add the official role.
- Auto-populate data
- [#161250744](https://www.pivotaltracker.com/story/show/161250744)
> #161250744 Add official and auto-populate roles

- app/controllers/fixtures_controller.rb
- spec/requests/fixtures_spec.rb
- Save the Auto Generated fixtures in one click of a button.
- Add fixture key to hold all the parameters.
- Fix fixtures tests.
- [#161145959](https://www.pivotaltracker.com/story/show/161145959)
> #161145959 Save the autogenerated fixtures in one click.

- app/controllers/commentaries_controller.rb
- app/models/commentary.rb
- app/models/event.rb
- app/policies/commentary_policy.rb
- config/routes.rb
- db/migrate/20180801100901_create_events.rb
- db/migrate/20180801100903_create_commentaries.rb
- db/schema.rb
- spec/factories/commentaries.rb
- spec/factories/events.rb
- spec/models/commentary_spec.rb
- spec/models/event_spec.rb
- spec/requests/commentaries_spec.rb
- Renames the events controller, policy and model to commentary and creates new event model.
- Rename the events controller, policy and model to commentary.
- Fix the tests
- Create a new event model with the following fields:  `name` and `description` to store data like `Yellow, Red, Goal, Assists, Own Goal` as events
- [#161291849](https://www.pivotaltracker.com/story/show/161291849)
> #161291849 Rename the events controller and model to commentary.

- app/models/fixture_squad.rb
- db/migrate/20181020194250_create_fixture_squads.rb
- db/schema.rb
- spec/models/fixture_squad_spec.rb
- creates the fixture_squad model for every fixture, league and team.
- Test the model.
- Create the fixture_squad model with first eleven and substitutes.
- [#161292256](https://www.pivotaltracker.com/story/show/161292256)
> #161292256 Create the fixture squad model

- app/controllers/sponsor_controller.rb
- app/models/sponsor.rb
- app/policies/sponsor_policy.rb
- config/routes.rb
- db/migrate/20180924191525_create_sponsors.rb
- db/migrate/20180924191551_create_leagues_sponsors.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/sponsors.rb
- spec/models/sponsor_spec.rb
- spec/requests/sponsor_spec.rb
- Enables the Admin/user to perform CRUD operations to sponsors.
- Test the sponsor requests and models.
- Update the schema for the league_sponsor and sponsors model changes.
- Test the model.
- Implement CRUD operations on the sponsor.
- [#160750695](https://www.pivotaltracker.com/story/show/160750695)
> #160750695 Enable users perform crud operations on sponsor.

- app/controllers/events_controller.rb
- app/policies/event_policy.rb
- config/routes.rb
- db/seeds.rb
- spec/requests/events_spec.rb
- Enables users to perform CRUD operations on events.
- Write tests for the events
- Write the policy
- Implement CRUD
- Write the automatic seed process
- [#161502534](https://www.pivotaltracker.com/story/show/161502534)
> #161502534 Enable users perform CRUD operations  on events.

- app/controllers/errors_controller.rb
- app/controllers/fixture_squad_controller.rb
- app/controllers/leagues_teams_controller.rb
- app/policies/fixture_squad_policy.rb
- config/routes.rb
- spec/factories/fixture_squad.rb
- spec/requests/fixture_squad_spec.rb
- Enables users to perform CRUD operations on fixture_squad.
- Write tests
- Write policies
- Make invalid record error more specific
- Implement CRUD on fixture_squad
- [#161502510](https://www.pivotaltracker.com/story/show/161502510)
> #161502510 Enable users perform CRUD operations  on fixture_squad.

- app/models/season.rb
- db/migrate/20190422163811_create_seasons.rb
- db/schema.rb
- db/seeds.rb
- spec/models/season_spec.rb
Creates seasons table.
- Create seasons table
- Write tests.
- Create seeds
[#161377709](https://www.pivotaltracker.com/story/show/161377709)
> Creates seasons table.

- app/controllers/api/v1/fixtures_controller.rb
- app/controllers/concerns/fixtures_concern.rb
- app/policies/fixture_policy.rb
- app/policies/fixtures_controller_policy.rb
DRY's up fixtures controller with concern and fixes policy bug.
> DRY up fixtures controller with a concern

- app/controllers/api/v1/errors_controller.rb
- app/controllers/api/v1/results_controller.rb
- app/models/result.rb
- app/policies/result_policy.rb
- config/routes.rb
- db/migrate/20190521150813_change_result_table_structure.rb
- db/schema.rb
- spec/factories/results.rb
- spec/models/result_spec.rb
- spec/requests/results_spec.rb
- Enables the Admin/referee to perform CRUD operations to sponsors.
- Test requests and models
- Add factory to generate results
- Add CRUD operations
- Add policies
- Add points logic
- Fix tests
- [#160342230](https://www.pivotaltracker.com/story/show/160342230)
> Enable CRUD operations on results of specific fixture

- app/controllers/api/v1/fixtures_controller.rb
- app/controllers/concerns/fixtures_concern.rb
- app/models/fixture.rb
- app/models/season.rb
- db/migrate/20190523111107_change_season_id_from_string_to_integer.rb
- db/migrate/20190523125632_change_fixtures_season_name_to_id.rb
- db/migrate/20190523135124_add_foreign_key_to_fixtures_from_seasons.rb
- db/schema.rb
- spec/factories/fixtures.rb
- spec/factories/seasons.rb
- spec/requests/commentaries_spec.rb
- spec/requests/fixture_squad_spec.rb
- spec/requests/fixtures_spec.rb
- spec/requests/results_spec.rb
Adds foreign key to fixture table related to seasons table.
[#165506204](https://www.pivotaltracker.com/story/show/165506204)
> Add foreign key to fixture table related to seasons table

- README.md
Updates the README with sample API endpoints
> Update the README with sample API endpoints

- .circleci/config.yml
- Gemfile
Upgrades ruby version from 2.4.1 to 2.5.3
> Upgrade ruby version from 2.4.1 to 2.5.3

- app/controllers/api/v1/commentaries_controller.rb
- app/models/commentary.rb
- app/models/fixture.rb
- app/models/fixture_squad.rb
- app/models/league.rb
- app/models/leagues_sponsor.rb
- app/models/leagues_team.rb
- app/models/player.rb
- app/models/result.rb
- app/models/season.rb
- app/models/sponsor.rb
- app/models/team.rb
- app/models/transfer.rb
- db/migrate/20190611111625_rename_commentary_foreign_keys.rb
- db/migrate/20190611120449_rename_fixture_squad_foreign_keys.rb
- spec/models/commentary_spec.rb
- spec/models/fixture_squad_spec.rb
- spec/models/league_spec.rb
- spec/models/leagues_sponsor_spec.rb
- spec/models/leagues_team_spec.rb
- spec/requests/commentaries_spec.rb
Fix relationships of all models
> Fix relationships of all models

- app/controllers/api/v1/commentaries_controller.rb
- app/controllers/api/v1/errors_controller.rb
- app/controllers/api/v1/events_controller.rb
- app/controllers/api/v1/fixture_squad_controller.rb
- app/controllers/api/v1/fixtures_controller.rb
- app/controllers/api/v1/leagues_controller.rb
- app/controllers/api/v1/leagues_teams_controller.rb
- app/controllers/api/v1/players_controller.rb
- app/controllers/api/v1/sponsor_controller.rb
- app/controllers/api/v1/teams_controller.rb
- app/controllers/api/v1/transfer_controller.rb
- app/controllers/concerns/standings.rb
- app/models/fixture.rb
- app/models/fixture_squad.rb
- config/routes.rb
- db/seeds.rb
- spec/requests/commentaries_spec.rb
- spec/requests/events_spec.rb
- spec/requests/fixture_squad_spec.rb
- spec/requests/fixtures_spec.rb
- spec/requests/leagues_spec.rb
- spec/requests/leagues_teams_controller_spec.rb
- spec/requests/players_spec.rb
- spec/requests/sponsor_spec.rb
- spec/requests/teams_spec.rb
- spec/requests/transfers_spec.rb
Restructuring routes to use resources
[#166537193](https://www.pivotaltracker.com/story/show/166537193)
> Restructure routes

- app/controllers/api/v1/commentaries_controller.rb
- app/controllers/api/v1/errors_controller.rb
- app/controllers/api/v1/events_controller.rb
- app/controllers/api/v1/fixture_squad_controller.rb
- app/controllers/api/v1/fixtures_controller.rb
- app/controllers/api/v1/league_standings_controller.rb
- app/controllers/api/v1/leagues_controller.rb
- app/controllers/api/v1/leagues_teams_controller.rb
- app/controllers/api/v1/players_controller.rb
- app/controllers/api/v1/register_controller.rb
- app/controllers/api/v1/results_controller.rb
- app/controllers/api/v1/sponsor_controller.rb
- app/controllers/api/v1/teams_controller.rb
- app/controllers/api/v1/transfer_controller.rb
- app/controllers/api/v1/user_token_controller.rb
- app/controllers/concerns/fixtures_concern.rb
Make modules independent of the controller class
[#168051257](https://www.pivotaltracker.com/story/show/168051257)
> Destructure controller modules

- README.md
Simplify API documentation
Organize API documentation on README.md better.
N/A
None
> #168971660 Simplify API documentation on README.md

- .circleci/config.yml
- app/controllers/api/v1/fixtures_controller.rb
- app/controllers/api/v1/leagues_controller.rb
- app/controllers/api/v1/leagues_teams_controller.rb
- app/controllers/api/v1/teams_controller.rb
- app/models/leagues_team.rb
- app/models/team.rb
- app/models/user.rb
- app/serializers/fixture_serializer.rb
- app/serializers/league_serializer.rb
- app/serializers/player_serializer.rb
- app/serializers/team_serializer.rb
- app/serializers/user_serializer.rb
- spec/factories/league_teams.rb
- spec/requests/fixtures_spec.rb
- spec/requests/leagues_spec.rb
- spec/requests/leagues_teams_controller_spec.rb
- spec/requests/players_spec.rb
- spec/requests/teams_spec.rb
- spec/requests/user_signup_spec.rb
Fixes failing specs and does some refactors
> Fixes and refactors
